[api]
port = "9000"
jwt_secret = "330ij1w3*t__enex=&6j0zjuw&t=w44mi1@_9j7_i!wqs9&7*m"

[database]
host = "localhost"
user = "postgres" 
pass = "postgres"
name = "api-gopvp"

[cors]
allow_origins = ["http://localhost:3000", "http://localhost"]
allow_methods = ["GET", "POST", "PUT", "PATCH", "DELETE"]
allow_headers = ["Origin", "Content-Type", "Accept"]
expose_headers = ["Content-Length"]
allow_credentials = true
max_age = 43200  # Em segundos, 12 horas

[ai]
api_key = "<API-KEY-OPENROUTER>"
endpoint = "https://openrouter.ai/api/v1/chat/completions"
model = "google/gemma-2-9b-it:free"