definitions:
  handlers.CredentialsRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.ErrorResponse:
    properties:
      error_code:
        type: string
      message:
        type: string
    type: object
  handlers.LoginResponse:
    properties:
      data:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CredentialsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Login
      tags:
      - login
swagger: "2.0"
