// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32
	Name string
}

type Objective struct {
	ID             int32
	UserID         int32
	CategoryID     sql.NullInt32
	SubcategoryID  sql.NullInt32
	HowAmI         string
	HowDoIWantToBe string
	WhatWillIDo    string
	WhenWillIDoIt  string
}

type Subcategory struct {
	ID   int32
	Name string
}

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	Password    string
	IsActive    bool
	IsStaff     bool
	IsSuperuser bool
	LastLogin   time.Time
	DateJoined  time.Time
}
